version: '3'

services:

  ingestion:
    build: ingestion/.
    env_file:
      - env_file
    networks:
      - ingestion_network
    restart: on-failure
    depends_on:
      - rabbit
    ports:
      - "80:5672"

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    env_file:
      - env_file
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - ingestion_network

  processing:
    build: processing/.
    env_file:
      - env_file
    networks:
      - ingestion_network
      - db_network
    restart: on-failure
    depends_on:
      - rabbit
    ports:
      - "81:5672"

  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - ./docker-entrypoint-initdb.d/init-tables.sh:/docker-entrypoint-initdb.d/init-tables.sh
    env_file:
      - env_file
    networks:
      - db_network

  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_network
      - web_network
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flaskapp

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  ingestion_network:
    driver: bridge

volumes:
  dbdata:
